FROM node:8 as node
WORKDIR /app
COPY package.json /app/
COPY yarn.lock /app/
RUN yarn install
COPY ./ /app/
ARG APP_ENV=functional
RUN yarn run build

FROM nginx:latest
COPY --from=node /app/dist/ /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf
