module.exports = {
  NODE_ENV: '"production"',
  GOOGLE_MAPS_API_KEY: '"GOOGLE_MAPS_API_KEY"',
  LEAFLET_MAP_APP_ID: '"LEAFLET_MAP_APP_ID"',
  LEAFLET_MAP_APP_CODE: '"LEAFLET_MAP_APP_CODE"',
  API_ENDPOINT: '"API_ENDPOINT"',
  API_PHONE_ENDPOINT: '"API_PHONE_ENDPOINT"'
};
