module.exports = {
  NODE_ENV: '"production"',
  GOOGLE_MAPS_API_KEY: '"GOOGLE_MAPS_API_KEY"',
  LEAFLET_MAP_APP_ID: '"OxegEAQ46ansqN9LtNd1"',
  LEAFLET_MAP_APP_CODE: '"86XV8M-pIbpy5TUa9H_Aww"',
  API_ENDPOINT: '"API_ENDPOINT"',
  API_PHONE_ENDPOINT: '"API_PHONE_ENDPOINT"'
};
