module.exports = {
  NODE_ENV: '"production"',
  GOOGLE_MAPS_API_KEY: '"AIzaSyAS7GowniFU4IZMZUEw0rVPyzY1EcWGXNU"',
  LEAFLET_MAP_APP_ID: '"OxegEAQ46ansqN9LtNd1"',
  LEAFLET_MAP_APP_CODE: '"86XV8M-pIbpy5TUa9H_Aww"',
  PITNEYBOWES_API_KEY: '"sFDDfMzkX8Ior1oIYR8PhxVm9MjwbGpy"',
  PITNEYBOWES_BASIC_AUTH_TOKEN: '"c0ZERGZNemtYOElvcjFvSVlSOFBoeFZtOU1qd2JHcHk6ckdCUmtObUF1YkxWS01CTw=="',
  API_ENDPOINT: '"http://api:5000"'
};
